services:
  database:
    image: postgres:13
    container_name: rabbimq-example-db
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq-example'
    environment:
      RABBITMQ_LOAD_DEFINITIONS: TRUE
      RABBITMQ_DEFINITIONS_FILE: "/etc/rabbitmq/definitions.json"
    ports:
      - "5672:5672"      # AMQP
      - "15672:15672"    # Management UI
    volumes:
      - ./.rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro #:ro = read only
      - ./.rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro